### ISSUE TITLE
Include and exclude settings seem to be broken

### ISSUE THREAD

**Issue by fisadev** [facundobatista/pyempaq#65]
(Using pyempaq v0.2.2, python 3.8.10)

If I specify the `include:` and/or `exclude:` fields in the `pyempaq.yaml` file, when trying to build the package I get this error:

```
simpyt ❯ pyempaq .
Parsing configuration in '.'
Problem(s) found in configuration file:
- 'exclude': extra fields not permitted
- 'include': extra fields not permitted
```

Example failing config:

```yaml
name: simpyt
exec:
  script: simpyt.py
requirements:
  - requirements.txt
include: 
  - simpyt.py
  - assets
  - example_user_dir
  - templates
  - README.md
exclude:
  - tests
```

I tried fixing it, found out that the `Config` class (from `config_manager.py`) doesn't have the required fields:

```python
class Config(ModelConfigDefaults, validate_all=False):
    """Definition of PyEmpaq's configuration."""

    name: str
    basedir: pathlib.Path  # the default for this is managed on YAML load time
    exec: Executor
    requirements: List[RelativeFile] = []
    dependencies: List[str] = []
```

Tried adding them:

```python
(...)
    include: List[RelativeFile] = []
    exclude: List[RelativeFile] = []
```

And the error went away, but then the settings seem to have no effect whatsoever, as the resulting package includes all the files from the source directory, not just the ones specified in `include:`, and even including the `tests` folder specified in `exclude:`.
